# Form implementation generated from reading ui file '/tmp/tmphm6h06_3/jddbusdebugger-4.2/jdDBusDebugger/ui/ConnectDialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ConnectDialog(object):
    def setupUi(self, ConnectDialog):
        ConnectDialog.setObjectName("ConnectDialog")
        ConnectDialog.resize(352, 155)
        self.verticalLayout = QtWidgets.QVBoxLayout(ConnectDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(parent=ConnectDialog)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=ConnectDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.name_edit = QtWidgets.QLineEdit(parent=ConnectDialog)
        self.name_edit.setObjectName("name_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.name_edit)
        self.label_2 = QtWidgets.QLabel(parent=ConnectDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.address_edit = QtWidgets.QLineEdit(parent=ConnectDialog)
        self.address_edit.setObjectName("address_edit")
        self.horizontalLayout_2.addWidget(self.address_edit)
        self.browse_button = QtWidgets.QPushButton(parent=ConnectDialog)
        self.browse_button.setObjectName("browse_button")
        self.horizontalLayout_2.addWidget(self.browse_button)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.formLayout)
        self.auto_connect_check_box = QtWidgets.QCheckBox(parent=ConnectDialog)
        self.auto_connect_check_box.setObjectName("auto_connect_check_box")
        self.verticalLayout.addWidget(self.auto_connect_check_box)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.ok_button = QtWidgets.QPushButton(parent=ConnectDialog)
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout.addWidget(self.ok_button)
        self.cancel_button = QtWidgets.QPushButton(parent=ConnectDialog)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ConnectDialog)
        QtCore.QMetaObject.connectSlotsByName(ConnectDialog)

    def retranslateUi(self, ConnectDialog):
        _translate = QtCore.QCoreApplication.translate
        ConnectDialog.setWindowTitle(_translate("ConnectDialog", "Connect"))
        self.label_3.setText(_translate("ConnectDialog", "You can connect here with your custom D-Bus address"))
        self.label.setText(_translate("ConnectDialog", "Name:"))
        self.label_2.setText(_translate("ConnectDialog", "Address:"))
        self.browse_button.setText(_translate("ConnectDialog", "Browse"))
        self.auto_connect_check_box.setText(_translate("ConnectDialog", "Auto connect on startup"))
        self.ok_button.setText(_translate("ConnectDialog", "OK"))
        self.cancel_button.setText(_translate("ConnectDialog", "Cancel"))
