# Form implementation generated from reading ui file '/tmp/tmphm6h06_3/jddbusdebugger-4.2/jdDBusDebugger/ui/ConnectServerDialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ConnectServerDialog(object):
    def setupUi(self, ConnectServerDialog):
        ConnectServerDialog.setObjectName("ConnectServerDialog")
        ConnectServerDialog.resize(467, 256)
        self.verticalLayout = QtWidgets.QVBoxLayout(ConnectServerDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(parent=ConnectServerDialog)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=ConnectServerDialog)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=ConnectServerDialog)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=ConnectServerDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.name_edit = QtWidgets.QLineEdit(parent=ConnectServerDialog)
        self.name_edit.setObjectName("name_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.name_edit)
        self.label_2 = QtWidgets.QLabel(parent=ConnectServerDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.server_box = QtWidgets.QComboBox(parent=ConnectServerDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.server_box.sizePolicy().hasHeightForWidth())
        self.server_box.setSizePolicy(sizePolicy)
        self.server_box.setObjectName("server_box")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.server_box)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.ok_button = QtWidgets.QPushButton(parent=ConnectServerDialog)
        self.ok_button.setEnabled(False)
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout.addWidget(self.ok_button)
        self.cancel_button = QtWidgets.QPushButton(parent=ConnectServerDialog)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ConnectServerDialog)
        QtCore.QMetaObject.connectSlotsByName(ConnectServerDialog)

    def retranslateUi(self, ConnectServerDialog):
        _translate = QtCore.QCoreApplication.translate
        ConnectServerDialog.setWindowTitle(_translate("ConnectServerDialog", "Connect to Server"))
        self.label_3.setText(_translate("ConnectServerDialog", "This will allow you to connect to a server started with Tools -> Start Server."))
        self.label_4.setText(_translate("ConnectServerDialog", "Your local network will automatically be searched for a running server."))
        self.label_5.setText(_translate("ConnectServerDialog", "If you wish to connect to a bus over the network without using the built-in server of jdDbusDebugger, you can do that in the Address connect dialog."))
        self.label.setText(_translate("ConnectServerDialog", "Name:"))
        self.label_2.setText(_translate("ConnectServerDialog", "Server:"))
        self.ok_button.setText(_translate("ConnectServerDialog", "OK"))
        self.cancel_button.setText(_translate("ConnectServerDialog", "Cancel"))
