'''
Module to specify constant values that are used in the application
'''

# default locations of the data to train and test sastadev
actualfolder = 'actual'
actualanalysisfolder = actualfolder
actual_sasfolder = actualfolder
analysiscomparisonfolder = 'analysiscomparison'
currentfolder = 'current'
currentanalysisfolder = currentfolder
current_sasfolder = currentfolder
corrfolder = 'corr'
nocorrfolder = 'nocorr'
overallsasfolder = '_SAS_overall'
previousanalysisfolder = 'previous'
previous_sasfolder = 'previous'
analysesfolder = 'analyses'
bronzefolder = 'bronze'
confidencefolder = 'confidence'
correctionref_folder = 'correctionref'
distancesheetname = 'Distance'
f1byuttidsheetname = 'F1byUttId'
figuresfolder = '_Figures'
formsfolder = 'forms'
indatafolder = 'indata'
intreebanksfolder = 'intreebanks'
loggingfolder = 'logging'
metasheetname = 'Meta'
outtreebanksfolder = 'outtreebanks'
overallsasfolder = '_SAS_overall'
resultsfolder = 'results'
sasfolder = 'SAS'
sasimpact_sheetname = 'SAS_impact'
sas_suffix = '_sas'
sas_summarysuffix = '_SASsummary'
scorefrqsheetname = 'ScoreFrq'
sentencessheetname = 'Sentences'
silverfolder = 'silver'
silverpermfolder = 'silverperm'
summarysheetname = 'Summary'
testsetsfolder = 'testsets'
uttinimpactsheetname = 'UttinImpact'
uttnotinimpactsheetname = 'UttNotinImpact'
uttsfoundsheetname = 'UttsFound'
dataset_treebanksfolder = 'dataset_treebanksfolder'
errorsummaryfolder = 'errorsummaries'
lemmafolder = 'lemmas'

analysissuffix = '_analysis'
analysistsvsuffix = '_analysis.tsv'
bronzesuffix = '_bronze'
byuttscoressuffix = '_scoresbyutt'
silversuffix = '_silver'
correctionrefsuffix = '_correctionref'
permprefix = 'perm_'
checksuffix = '_platinum.check.tsv'
checkeditedsuffix = '_platinum.check-edited.tsv'
platinumsuffix = '.platinum.tsv'
platinumeditedsuffix = '.platinum-edited.tsv'

errorsummarysuffix = '_errorsummary'
errorloggingsuffix = '_errorlogging'