'''
 Generated by EZX Code Generator  
Date: 11/10/22 
'''


from iserver.EzxMsg import EzxMsg, EzxMsgMeta
from iserver.msgs import *
from iserver.enums import api




class OrderStatus(EzxMsg, metaclass=EzxMsgMeta):


	def __init__(self, **kwargs):
		self.quoteID : str = None
		self.handlInstr : int = None
		self.routerOrderID : int = None
		self.seqNo : int = None
		self.version : int = None
		self.settlementType : int = None
		self.side : int = None
		self.timeInForce : int = None
		self.orderQty : float = None
		self.price : float = None
		self.stopPrice : float = None
		self.ordType : str = None
		self.idSource : str = None
		self.account : str = None
		self.clientOrderID : str = None
		self.commission : float = None
		self.coveredOrUncovered : int = None
		self.customerOrFirm : int = None
		self.currency : str = None
		self.destination : str = None
		self.exDest : str = None
		self.execBroker : str = None
		self.execInstr : str = None
		self.expireDate : str = None
		self.expireTime : str = None
		self.locateReqd : str = None
		self.myID : str = None
		self.reported : int = None
		self.securityID : str = None
		self.securityType : str = None
		self.symbol : str = None
		self.symbolsfx : str = None
		self.text : str = None
		self.userInfo : str = None
		self.senderSubID : str = None
		self.targetSubID : str = None
		self.importFileName : str = None
		self.importTimeStamp : str = None
		self.importJobName : str = None
		self.pegDiff : float = None
		self.discretionaryOffset : float = None
		self.minQty : float = None
		self.maxFloor : float = None
		self.dispRange : float = None
		self.cumQty : float = None
		self.event : str = None
		self.leavesQty : float = None
		self.optAttribute : str = None
		self.pendReq : str = None
		self.state : str = None
		self.timeStamp : str = None
		self.totExec : float = None
		self.userName : str = None
		self.maturityMonthYear : str = None
		self.maturityDay : int = None
		self.clearingAcct : str = None
		self.carryFirmSubAcct : str = None
		self.conditionExpiry : str = None
		self.putOrCall : int = None
		self.strikePx : float = None
		self.mpID : str = None
		self.clientOrderLinkID : str = None
		self.openClose : str = None
		self.securityExchange : str = None
		self.ezxClientOrderID : int = None
		self.ezxClientOrderVersion : int = None
		self.msgOrigin : int = None
		self.clientNameID : int = None
		self.basketID : str = None
		self.brokerOrderID : str = None
		self.totCumQty : float = None
		self.totTotExec : float = None
		self.cfiCode : str = None
		self.refID : str = None
		self.ratioQty : int = None
		self.positionEffect : str = None
		self.tradingSession : str = None
		self.myClearingAccount : str = None
		self.ssOrderID : int = None
		self.linkedInboundOrderID : int = None
		self.reportFills : int = None
		self.futSettDate : str = None
		self.onBehalfOfCompID : str = None
		self.omsOrdType : str = None
		self.originalSide : int = None
		self.creditLimit : float = None
		self.creditUsed : float = None
		self.positionLimit : int = None
		self.positionLimitUsed : int = None
		self.clientCreditLimit : float = None
		self.clientCreditUsed : float = None
		self.clientPositionLimit : int = None
		self.clientPositionLimitUsed : int = None
		self.requestVersion : int = None
		super(OrderStatus, self).__init__(**kwargs)

