'''
 Generated by EZX Code Generator  
Date: 04/18/22 
'''


from iserver.EzxMsg import EzxMsg, EzxMsgMeta
from iserver.msgs import *
from iserver.enums import api




class OrderInfoRequest(EzxMsg, metaclass=EzxMsgMeta):


	def __init__(self, **kwargs):
		self.infoType : int = None
		self.myID : str = None
		self.routerOrderID : int = None
		super(OrderInfoRequest, self).__init__(**kwargs)
		self.msg_type = api.IserverMsgType.APPLICATION.value
		self.msg_subtype = api.IserverMsgSubType.ORDERINFO_REQUEST.value

