# Stub file for type hints

import platform
import subprocess
import uuid
import hashlib
from typing import Dict, Optional

class WXDevices:
    @staticmethod
    def get_system(): ...
    @staticmethod
    def get_node(): ...
    @staticmethod
    def get_release(): ...
    @staticmethod
    def get_version(): ...
    @staticmethod
    def get_machine(): ...
    @staticmethod
    def get_processor(): ...
    @staticmethod
    def get_system_info(): ...
    @staticmethod
    def get_device_mac(): ...
    @staticmethod
    def get_windows_machine_guid(): ...
    @staticmethod
    def get_linux_machine_id(): ...
    @staticmethod
    def get_macos_serial_number(): ...
    @staticmethod
    def generate_fingerprint(): ...
    @staticmethod
    def get_device_id(): ...
