
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-06-26T04:20:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "95e1eb84295806b1bb4d57ec580ee03ef6192b54",
 "version": "1.33.1.post0.dev17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
