"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from tofupilot_py.types import BaseModel
from typing import Literal
from typing_extensions import TypedDict


Importer = Literal["OPENHTF"]


class RunCreateFromFileRequestTypedDict(TypedDict):
    upload_id: str
    importer: Importer


class RunCreateFromFileRequest(BaseModel):
    upload_id: str

    importer: Importer


class RunCreateFromFileResponseTypedDict(TypedDict):
    r"""Run imported successfully"""

    id: str
    r"""The ID of the created run"""


class RunCreateFromFileResponse(BaseModel):
    r"""Run imported successfully"""

    id: str
    r"""The ID of the created run"""
