# This file was automatically generated by WaveSQL.
# You are free to modify this file as needed.
#
# Copyright 2025 eelus1ve and the WaveTeam
# GitHub: https://github.com/eelus1ve
# Repo: https://github.com/WaveTeamDevs/WaveSQL
# License: Apache-2.0 (see https://www.apache.org/licenses/LICENSE-2.0)

from .database import db

__all__ = ['db']
