# Stub file for type hints

import logging.config
import json
import os
from typing import Dict, Optional, Union
from pywxbase.helper.wx_paths import WXPaths

class WXLogger:
    def __init__(self, custom_config: Optional[Union[Dict, str]] = None): ...
    def set_custom_logger(self, custom_config: Optional[Union[Dict, str]] = None, default_logger: str = None): ...
    def set_default_logger(self, default_logger: str): ...
    def get_logger(self, name: str = None): ...
    def _init_logger(self, custom_config: Optional[Union[Dict, str]] = None, default_logger: str = None): ...
    def set_level(self, level, logger_name: str = None): ...
    def debug(self, msg, logger_name: str = None, *args, **kwargs): ...
    def info(self, msg, logger_name: str = None, *args, **kwargs): ...
    def warning(self, msg, logger_name: str = None, *args, **kwargs): ...
    def warn(self, msg, logger_name: str = None, *args, **kwargs): ...
    def error(self, msg, logger_name: str = None, *args, **kwargs): ...
    def critical(self, msg, logger_name: str = None, *args, **kwargs): ...
