# Stub file for type hints

from typing import Optional

class WXStrings:
    @staticmethod
    def to_upper(text: Optional[str]): ...
    @staticmethod
    def to_lower(text: Optional[str]): ...
    @staticmethod
    def to_title(text: Optional[str]): ...
    @staticmethod
    def strip_spaces(text: Optional[str]): ...
    @staticmethod
    def remove_all_spaces(text: Optional[str]): ...
    @staticmethod
    def reverse(text: Optional[str]): ...
    @staticmethod
    def length(text: Optional[str]): ...
    @staticmethod
    def replace(text: Optional[str], old: Optional[str], new: Optional[str]): ...
    @staticmethod
    def is_empty(text: Optional[str]): ...
    @staticmethod
    def is_not_empty(text: Optional[str]): ...
