"""
Generated by inkly v1.0.0
Do not edit this file directly. Make changes to the original OpenAPI specification.

StatusEnum enum definition
"""

from enum import Enum


class StatusEnum(Enum):
    """ペットのステータス"""
    AVAILABLE = "available"
    PENDING = "pending"
    SOLD = "sold"
