"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from moovio_sdk import utils
from moovio_sdk.types import BaseModel
import pydantic
from typing import Dict, Optional
from typing_extensions import Annotated


class OnboardingInviteErrorData(BaseModel):
    return_url: Annotated[Optional[str], pydantic.Field(alias="returnURL")] = None

    terms_of_service_url: Annotated[
        Optional[str], pydantic.Field(alias="termsOfServiceURL")
    ] = None

    scopes: Optional[Dict[str, str]] = None

    capabilities: Optional[Dict[str, str]] = None

    fee_plan_codes: Annotated[
        Optional[Dict[str, str]], pydantic.Field(alias="feePlanCodes")
    ] = None


class OnboardingInviteError(Exception):
    data: OnboardingInviteErrorData

    def __init__(self, data: OnboardingInviteErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, OnboardingInviteErrorData)
