'''
 Generated by EZX Code Generator  
Date: 04/18/22 
'''


from iserver.EzxMsg import EzxMsg, EzxMsgMeta
from iserver.msgs import *
from iserver.enums import api
from iserver.msgs.AllocationStatus import AllocationStatus




class AllocationResponse(AllocationStatus, metaclass=EzxMsgMeta):


	def __init__(self, **kwargs):
		super(AllocationResponse, self).__init__(**kwargs)
		self.msg_type = api.IserverMsgType.APPLICATION.value
		self.msg_subtype = api.IserverMsgSubType.ALLOCATION_RESPONSE.value

