'''
 Generated by EZX Code Generator  
Date: 04/18/22 
'''


from iserver.EzxMsg import EzxMsg, EzxMsgMeta
from iserver.msgs import *
from iserver.enums import api




class ForgotPasswordResponse(EzxMsg, metaclass=EzxMsgMeta):


	def __init__(self, **kwargs):
		self.returnCode : int = None
		self.returnDesc : str = None
		super(ForgotPasswordResponse, self).__init__(**kwargs)
		self.msg_type = api.IserverMsgType.SESSION.value
		self.msg_subtype = api.IserverMsgSubType.FORGOTPASSWORD_RESPONSE.value

