'''
 Generated by EZX Code Generator  
Date: 03/12/25 
'''


from iserver.EzxMsg import EzxMsg, EzxMsgMeta
from iserver.msgs import *
from iserver.enums import api




class SecurityLegInfo(EzxMsg, metaclass=EzxMsgMeta):


	def __init__(self, **kwargs):
		self.symbol : str = None
		self.side : int = None
		self.price : float = None
		self.securityID : str = None
		self.securityIDSource : str = None
		self.ratioQty : int = None
		self.optionDelta : float = None
		super(SecurityLegInfo, self).__init__(**kwargs)

