# coding: utf-8

"""
    Core Operations

    The Sparkfly Platform provides a full lifecycle for promotions and rewards from creation to distribution to settlement. The platform integrates in real-time at the point-of-sale and provides item level discounting and tracking. The capabilities of the Sparkfly Platform are available through the use of the Sparkfly Platform API.  The Sparkfly documentation site is under development. If the documentation you're after isn't available here, please contact support@sparkfly.com and we will get you what you need.

    The version of the OpenAPI document: 1.0
    Contact: support@sparkfly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.eligible_item_sets_api import EligibleItemSetsApi


class TestEligibleItemSetsApi(unittest.TestCase):
    """EligibleItemSetsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EligibleItemSetsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_offers_offer_id_eligible_item_sets_id(self) -> None:
        """Test case for delete_offers_offer_id_eligible_item_sets_id

        Remove an Eligible Item Set
        """
        pass

    def test_get_offers_offer_id_eligible_item_sets(self) -> None:
        """Test case for get_offers_offer_id_eligible_item_sets

        List all Eligible Item Sets
        """
        pass

    def test_get_offers_offer_id_eligible_item_sets_id(self) -> None:
        """Test case for get_offers_offer_id_eligible_item_sets_id

        Get an Eligible Item Set
        """
        pass

    def test_post_offers_offer_id_eligible_item_sets(self) -> None:
        """Test case for post_offers_offer_id_eligible_item_sets

        Create an Eligible Item Set
        """
        pass

    def test_put_offers_offer_id_eligible_item_sets_id(self) -> None:
        """Test case for put_offers_offer_id_eligible_item_sets_id

        Update an Eligible Item Set
        """
        pass


if __name__ == '__main__':
    unittest.main()
