samples = [
    {"utterance": "Turn {DeviceAction} the {DeviceName}"},
    {"utterance": "Switch {DeviceAction} the {DeviceName}"},
    {"utterance": "{DeviceAction} the {DeviceName}"},
    {"utterance": "Set the {DeviceName} to {DeviceValue}"},
    {"utterance": "Adjust the {DeviceName} to {DeviceValue}"},
    {"utterance": "Change the {DeviceName} to {DeviceValue}"},
    {"utterance": "Make the {DeviceName} {DeviceAction}"},
    {"utterance": "Set temperature to {DeviceValue} degrees"},
    {"utterance": "Change thermostat to {DeviceValue}"},
    {"utterance": "Adjust house temperature to {DeviceValue}"},
    {"utterance": "Make it {DeviceValue} degrees in the {RoomName}"},
    {"utterance": "Turn {DeviceAction} lights in the {RoomName}"},
    {"utterance": "Dim the lights in {RoomName} to {DeviceValue} percent"},
    {"utterance": "Brighten the {DeviceName} in {RoomName}"},
    {"utterance": "Set {DeviceName} brightness to {DeviceValue}"},
    {"utterance": "What's the weather like {timeframe}"},
    {"utterance": "What's the weather forecast for {timeframe}"},
    {"utterance": "How's the weather {timeframe}"},
    {"utterance": "Will it rain {timeframe}"},
    {"utterance": "Is it going to be sunny {timeframe}"},
    {"utterance": "What's the temperature outside {timeframe}"},
    {"utterance": "What's the weather like in {location} {timeframe}"},
    {"utterance": "How hot will it be {timeframe}"},
    {"utterance": "How cold will it be {timeframe}"},
    {"utterance": "Will I need an umbrella {timeframe}"},
    {"utterance": "What's the forecast for {location} {timeframe}"},
    {"utterance": "Tell me about the weather {timeframe}"},
    {"utterance": "Is it raining outside"},
    {"utterance": "What's the humidity {timeframe}"},
    {"utterance": "Will it snow {timeframe}"},
    {"utterance": "Set the temperature to 72 degrees"},
    {"utterance": "Make it warmer in here"},
    {"utterance": "Turn up the thermostat"},
    {"utterance": "Set a timer for {duration}"},
    {"utterance": "Start a timer for {duration}"},
    {"utterance": "Create a timer for {duration}"},
    {"utterance": "Remind me in {duration}"},
    {"utterance": "Set an alarm for {duration}"},
    {"utterance": "Wake me up in {duration}"},
    {"utterance": "Set a countdown for {duration}"},
    {"utterance": "Give me a {duration} timer"},
    {"utterance": "Remind me to {action} in {duration}"},
    {"utterance": "Set a reminder to {action} for {duration} from now"},
    {"utterance": "Create a calendar event for {action}"},
    {"utterance": "Schedule {action} on my calendar"},
    {"utterance": "Add {action} to my schedule"},
    {"utterance": "Set up a reminder for {action}"},
    {"utterance": "Alert me when {duration} has passed"},
    {"utterance": "Calculate 6 times 4"},
    {"utterance": "What is 10 divided by 2"},
    {"utterance": "Compute 5 plus 3"},
    {"utterance": "What's 7 multiplied by 8"},
    {"utterance": "Solve 12 minus 5"},
    {"utterance": "Calculate {expression}"},
    {"utterance": "What is {number1} times {number2}"},
    {"utterance": "Compute {number1} plus {number2}"},
    {"utterance": "What's {number1} divided by {number2}"},
    {"utterance": "Tell me about {topic}"},
    {"utterance": "How do I {action}"},
    {"utterance": "What's the meaning of {term}"},
    {"utterance": "Who is {person}"},
    {"utterance": "When was {event}"},
    {"utterance": "Why does {subject} {verb}"},
]
