# coding: utf-8

"""
    Speechall API

    The Speechall REST API provides powerful and flexible speech-to-text capabilities. It allows you to transcribe audio files using various underlying STT providers and models, optionally apply custom text replacement rules, and access results in multiple formats. The API includes standard endpoints for transcription and endpoints compatible with the OpenAI API structure. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from speechall.models.transcription_model_identifier import TranscriptionModelIdentifier  # noqa: E501

class TestTranscriptionModelIdentifier(unittest.TestCase):
    """TranscriptionModelIdentifier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTranscriptionModelIdentifier(self):
        """Test TranscriptionModelIdentifier"""
        # inst = TranscriptionModelIdentifier()

if __name__ == '__main__':
    unittest.main()
