# coding: utf-8

"""
    Speechall API

    The Speechall REST API provides powerful and flexible speech-to-text capabilities. It allows you to transcribe audio files using various underlying STT providers and models, optionally apply custom text replacement rules, and access results in multiple formats. The API includes standard endpoints for transcription and endpoints compatible with the OpenAI API structure. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from speechall.api.replacement_rules_api import ReplacementRulesApi  # noqa: E501


class TestReplacementRulesApi(unittest.TestCase):
    """ReplacementRulesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReplacementRulesApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_create_replacement_ruleset(self) -> None:
        """Test case for create_replacement_ruleset

        Create a reusable set of text replacement rules.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
