# Generated by Django 5.1.4 on 2024-12-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequestResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the entry was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the entry was updated')),
                ('method', models.CharField(max_length=10)),
                ('api_request_data', models.TextField(blank=True, null=True)),
                ('api_response_data', models.TextField(blank=True, null=True)),
                ('response_status', models.PositiveIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'API Request-Response Log',
            },
        ),
    ]
