#+title: bisos.bx-bases: Python scripts (Command Services) used for bootstrapping the BISOS environment.

Panel Controls:: [[elisp:(show-all)][Show-All]]  [[elisp:(org-shifttab)][Overview]]  [[elisp:(progn (org-shifttab) (org-content))][Content]] | [[elisp:(delete-other-windows)][(1)]] | [[elisp:(progn (save-buffer) (kill-buffer))][S&Q]] [[elisp:(save-buffer)][Save]] [[elisp:(kill-buffer)][Quit]] [[elisp:(bury-buffer)][Bury]]
Links: [[file:./panels/_nodeBase_/fullUsagePanel-en.org]] (Package Panel)

* Overview
bx-bases: python scripts (Command Services)
are used for bootstrapping the BISOS (ByStar Internet Services OS)
environment.

bx-pip and bx-bases are CS scripts that will normally be installed in  /usr/local/bin.
bx-bases then can create /bisos and that allows for bx-pip to thereafter to
install into bystar instead of /usr/local/bin.


* Table of Contents     :TOC:
- [[#overview][Overview]]
- [[#about-bisos-----bystar-internet-services-operating-system][About BISOS --- ByStar Internet Services Operating System]]
- [[#uses-of-bisosbx-bases][Uses of bisos.bx-bases]]
- [[#installation][Installation]]
  - [[#with-pip][With pip]]
  - [[#with-pipx][With pipx]]
- [[#usage][Usage]]
  - [[#locally-system-command-line][Locally (system command-line)]]
- [[#documentation][Documentation]]
  - [[#bisosbx-bases-blee-panels][bisos.bx-bases Blee-Panels]]
- [[#support][Support]]

* About BISOS --- ByStar Internet Services Operating System

Layered on top of Debian, *BISOS*: (By* Internet Services Operating System) is a
unified and universal framework for developing both internet services and
software-service continuums that use internet services. See [[https://github.com/bxGenesis/start][Bootstrapping
ByStar, BISOS and Blee]] for information about getting started with BISOS.

bisos.facter/ is a small piece of a much bigger picture. *BISOS* is a
foundation for *The Libre-Halaal ByStar Digital Ecosystem* which is described as
a cure for losses of autonomy and privacy that we are experiencing in a book
titled: [[https://github.com/bxplpc/120033][Nature of Polyexistentials]]

* Uses of bisos.bx-bases

Within BISOS, the installation process uses bx-bases.

* Installation

The sources for the  bisos.facter pip package is maintained at:
https://github.com/bisos-pip/bx-bases.

The bisos.bx-bases pip package is available at PYPI as
https://pypi.org/project/bisos.bx-bases

You can install bisos.bx-bases with pip or pipx.

** With pip

If you need access to bisos.facter as a python module, you can install it with pip:

#+begin_src bash
pip install bisos.bx-bases
#+end_src

** With pipx

If you only need access to bisos.facter on command-line, you can install it with pipx:

#+begin_src bash
pipx install bisos.bx-bases
#+end_src

The following commands are made available:
- bx-bases

* Usage

** Locally (system command-line)

#+begin_src bash
bin/bx-bases
#+end_src

* Documentation

Part of ByStar Digital Ecosystem [[http://www.by-star.net]].

This module's primary documentation is in
[[http://www.by-star.net/PLPC/180047]]

** bisos.bx-bases Blee-Panels

bisos.bx-bases Blee-Panles are in ./panels directory.
From within Blee and BISOS these panles are accessible under the
Blee "Panels" menu.

* Support

For support, criticism, comments and questions; please contact the
author/maintainer\\
[[http://mohsen.1.banan.byname.net][Mohsen Banan]] at:
[[http://mohsen.1.banan.byname.net/contact]]


