'''
 Generated by EZX Code Generator  
Date: 04/18/22 
'''


from iserver.EzxMsg import EzxMsg, EzxMsgMeta
from iserver.msgs import *
from iserver.enums import api




class DeleteClientOrder(EzxMsg, metaclass=EzxMsgMeta):


	def __init__(self, **kwargs):
		self.ezxClientOrderID : int = None
		self.clientNameID : int = None
		super(DeleteClientOrder, self).__init__(**kwargs)
		self.msg_type = api.IserverMsgType.APPLICATION.value
		self.msg_subtype = api.IserverMsgSubType.DELETE_CLIENT_ORDER.value

