'''
 Generated by EZX Code Generator  
Date: 03/28/25 
'''


from iserver.EzxMsg import EzxMsg, EzxMsgMeta
from iserver.msgs import *
from iserver.enums import api
from iserver.msgs.SecurityRequestInfo import SecurityRequestInfo

from .SecurityLegInfo import SecurityLegInfo



class SecurityDefinitionResponseApi(SecurityRequestInfo, metaclass=EzxMsgMeta):

	__block_fields__ = {
		'SLB' : Field('legList', 'SLB', noop_decode_func, update_list_item), 
	}

	def __init__(self, **kwargs):
		self.seqNo : int = None
		self.securityResponseID : int = None
		self.state : str = None
		self.currency : str = None
		self.securityID : str = None
		self.legList : list[SecurityLegInfo] = None
		super(SecurityDefinitionResponseApi, self).__init__(**kwargs)
		self.msg_type = api.IserverMsgType.APPLICATION.value
		self.msg_subtype = api.IserverMsgSubType.SECURITY_DEFINITION_RESPONSE.value

