'''
 Generated by EZX Code Generator  
Date: 04/18/22 
'''


from iserver.EzxMsg import EzxMsg, EzxMsgMeta
from iserver.msgs import *
from iserver.enums import api
from iserver.msgs.GroupAccountChange import GroupAccountChange




class UpdateGroupSettings(GroupAccountChange, metaclass=EzxMsgMeta):


	def __init__(self, **kwargs):
		self.overRideGroupRestriction : int = None
		super(UpdateGroupSettings, self).__init__(**kwargs)
		self.msg_type = api.IserverMsgType.COMMAND.value
		self.msg_subtype = api.IserverMsgSubType.UPDATE_GROUP_SETTINGS.value

