#+title: bisos.gcipher: from debian dpkg to pypi module conversion.




* Overview

gcipher: from debian dpkg to pypi module conversion.


* Package Documentation At Github

The information below is a subset of the full of documentation for this bisos-pip package.
More complete documentation is available at: https://github.com/bisos-pip/gcipher-cs


* Table of Contents     :TOC:
- [[#overview][Overview]]
- [[#package-documentation-at-github][Package Documentation At Github]]
- [[#installation][Installation]]
  - [[#installation-with-pip][Installation With pip]]
  - [[#installation-with-pipx][Installation With pipx]]
- [[#support][Support]]

* Installation

The sources for the  bisos.gcipher pip package is maintained at:
https://github.com/bisos-pip/gcipher.

The bisos.gcipher pip package is available at PYPI as
https://pypi.org/project/bisos.gcipher

You can install bisos.gcipher with pip or pipx.

** Installation With pip

If you need access to bisos.gcipher as a python module, you can install it with pip:

#+begin_src bash
pip install bisos.gcipher
#+end_src

** Installation With pipx

If you only need access to bisos.gcipher as a command on command-line, you can install it with pipx:

#+begin_src bash
pipx install bisos.gcipher
#+end_src

The following commands are made available:
- gcipher


* Support

For support, criticism, comments and questions; please contact the
author/maintainer\\
[[http://mohsen.1.banan.byname.net][Mohsen Banan]] at:
[[http://mohsen.1.banan.byname.net/contact]]





