#+Title: bisos.githubApi:  BISOS Capabilities Bundles -- Abstraction, Specification and Materialization




* Overview

bisos.githubApi is a python package for BISOS Capabilities Bundles -- Abstraction, Specification and
Materialization.



* Package Documentation At Github

The information below is a subset of the full of documentation for this bisos-pip package.
More complete documentation is available at: https://github.com/bisos-pip/githubApi-cs


* Realted Resources

| bisos Capabilities Panel | file:/panels/capabilities/_nodeBase_/fullUsagePanel-en.org |
|                          |                                                                |


* Table of Contents     :TOC:
- [[#overview][Overview]]
- [[#package-documentation-at-github][Package Documentation At Github]]
- [[#realted-resources][Realted Resources]]
- [[#installation][Installation]]
  - [[#installation-with-pip][Installation With pip]]
  - [[#installation-with-pipx][Installation With pipx]]
- [[#part-of-bisos-and-bystar-----bystar-internet-services-operating-system][Part of BISOS and ByStar --- ByStar Internet Services Operating System]]
- [[#bisosgithubapi-as-a-standalone-piece-of-bisos][bisos.githubApi as a Standalone Piece of BISOS]]
- [[#documentation-and-blee-panels][Documentation and Blee-Panels]]
  - [[#bisosgithubapi-blee-panels][bisos.githubApi Blee-Panels]]
- [[#support][Support]]

* Installation

The sources for the  bisos.githubApi pip package is maintained at:
https://github.com/bisos-pip/githubApi.

The bisos.githubApi pip package is available at PYPI as
https://pypi.org/project/bisos.githubApi

You can install bisos.githubApi with pip or pipx.

** Installation With pip

If you need access to bisos.githubApi as a python module, you can install it with pip:

#+begin_src bash
pip install bisos.githubApi
#+end_src

** Installation With pipx

If you only need access to bisos.githubApi as a command on command-line, you can install it with pipx:

#+begin_src bash
pipx install bisos.githubApi
#+end_src

The following commands are made available:
./bin/githubApiAccess.py
./bin/githubApiReports.py


* Part of BISOS and ByStar --- ByStar Internet Services Operating System

Layered on top of Debian, *BISOS*: (By* Internet Services Operating System) is a
unified and universal framework for developing both internet services and
software-service continuums that use internet services. See [[https://github.com/bxGenesis/start][Bootstrapping
ByStar, BISOS and Blee]] for information about getting started with BISOS.\\
*BISOS* is a foundation for *The Libre-Halaal ByStar Digital Ecosystem* which is
described as a cure for losses of autonomy and privacy in a book titled: [[https://github.com/bxplpc/120033][Nature
of Polyexistentials]]

/bisos.githubApi/ is part of BISOS.

* bisos.githubApi as a Standalone Piece of BISOS

bisos.githubApi is a standalone piece of BISOS. It can be used as a self-contained
Python package separate from BISOS. Follow the installation and usage
instructions below for your own use.


* Documentation and Blee-Panels

bisos.githubApi is part of ByStar Digital Ecosystem [[http://www.by-star.net]].

This module's primary documentation is in the form of Blee-Panels.
Additional information is also available in: [[http://www.by-star.net/PLPC/180047]]

** bisos.githubApi Blee-Panels

bisos.githubApi Blee-Panels are in ./panels directory.
From within Blee and BISOS these panels are accessible under the
Blee "Panels" menu.

* Support

For support, criticism, comments and questions; please contact the
author/maintainer\\
[[http://mohsen.1.banan.byname.net][Mohsen Banan]] at:
[[http://mohsen.1.banan.byname.net/contact]]





