# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x11rtix.types.common\x1a\x19google/protobuf/any.proto\" \n\x08Metadata\x12\x14\n\x0ctimestamp_ns\x18\x01 \x01(\x04\"^\n\x06Packet\x12-\n\x08metadata\x18\x01 \x01(\x0b\x32\x1b.rtix.types.common.Metadata\x12%\n\x07payload\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"E\n\x07Outcome\x12)\n\x06status\x18\x01 \x01(\x0e\x32\x19.rtix.types.common.Status\x12\x0f\n\x07message\x18\x02 \x01(\t*/\n\x06Status\x12\x0b\n\x07RUNNING\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x0b\n\x07\x46\x41ILURE\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=263
  _globals['_STATUS']._serialized_end=310
  _globals['_METADATA']._serialized_start=62
  _globals['_METADATA']._serialized_end=94
  _globals['_PACKET']._serialized_start=96
  _globals['_PACKET']._serialized_end=190
  _globals['_OUTCOME']._serialized_start=192
  _globals['_OUTCOME']._serialized_end=261
# @@protoc_insertion_point(module_scope)
