# Autogenerated by devscripts/update-version.py

__version__ = '2025.06.26.233029'

RELEASE_GIT_HEAD = '06c1a8cdffe14050206683253726875144192ef5'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2025.06.26.233029dev'
