# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SupportedVersions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'component_type': 'str',
        'supported_versions': 'list[str]'
    }

    attribute_map = {
        'component_type': 'componentType',
        'supported_versions': 'supportedVersions'
    }

    def __init__(self, component_type=None, supported_versions=None):  # noqa: E501
        """SupportedVersions - a model defined in Swagger"""  # noqa: E501
        self._component_type = None
        self._supported_versions = None
        self.discriminator = None
        self.component_type = component_type
        self.supported_versions = supported_versions

    @property
    def component_type(self):
        """Gets the component_type of this SupportedVersions.  # noqa: E501


        :return: The component_type of this SupportedVersions.  # noqa: E501
        :rtype: str
        """
        return self._component_type

    @component_type.setter
    def component_type(self, component_type):
        """Sets the component_type of this SupportedVersions.


        :param component_type: The component_type of this SupportedVersions.  # noqa: E501
        :type: str
        """
        if component_type is None:
            raise ValueError("Invalid value for `component_type`, must not be `None`")  # noqa: E501
        allowed_values = ["KUBERNETES"]  # noqa: E501
        if component_type not in allowed_values:
            raise ValueError(
                "Invalid value for `component_type` ({0}), must be one of {1}"  # noqa: E501
                .format(component_type, allowed_values)
            )

        self._component_type = component_type

    @property
    def supported_versions(self):
        """Gets the supported_versions of this SupportedVersions.  # noqa: E501


        :return: The supported_versions of this SupportedVersions.  # noqa: E501
        :rtype: list[str]
        """
        return self._supported_versions

    @supported_versions.setter
    def supported_versions(self, supported_versions):
        """Sets the supported_versions of this SupportedVersions.


        :param supported_versions: The supported_versions of this SupportedVersions.  # noqa: E501
        :type: list[str]
        """
        if supported_versions is None:
            raise ValueError("Invalid value for `supported_versions`, must not be `None`")  # noqa: E501

        self._supported_versions = supported_versions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SupportedVersions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SupportedVersions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
