# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
# If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
# © 2025 cswimr

# This file is automatically generated on build, do not edit!
# Do not commit this file to source control!

from furl import furl

from .metadata import Repository, SemVer, TidegearMeta

meta = TidegearMeta(
    version=SemVer.from_tuple((1, 0, 6)),
    repository=Repository(
        owner="cswimr",
        name="tidegear",
        url=furl("https://c.csw.im/cswimr/tidegear"),
    ),
)

version = meta.version
__version__ = str(meta.version)
