
__all__ = [
    "MIN_FLOAT",
    "MAX_FLOAT",
    "FLOAT_EPSILON",
    "MIN_BANDWIDTH",
    "MAX_BANDWIDTH",
    "MIN_LATENCY",
    "MAX_LATENCY",
    "MIN_AVAILABILITY",
    "MAX_AVAILABILITY",
    "DEFAULT_SIM_PATH",
    "DEFAULT_REPORT_TYPE",
]

DEFAULT_REPORT_TYPE: str
