# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: apexnova/notification/notification_service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'apexnova/notification/notification_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from apexnova.notification import notification_pb2 as apexnova_dot_notification_dot_notification__pb2
from apexnova.stub import authorization_context_pb2 as apexnova_dot_stub_dot_authorization__context__pb2
from apexnova.stub import response_pb2 as apexnova_dot_stub_dot_response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0apexnova/notification/notification_service.proto\x12\x08\x61pexnova\x1a(apexnova/notification/notification.proto\x1a)apexnova/stub/authorization_context.proto\x1a\x1c\x61pexnova/stub/response.proto\"\x8a\x01\n\x10SendEmailRequest\x12=\n\x15\x61uthorization_context\x18\x01 \x01(\x0b\x32\x1e.apexnova.AuthorizationContext\x12\x37\n\x12\x65mail_notification\x18\x02 \x01(\x0b\x32\x1b.apexnova.EmailNotification\"\x84\x01\n\x0eSendSMSRequest\x12=\n\x15\x61uthorization_context\x18\x01 \x01(\x0b\x32\x1e.apexnova.AuthorizationContext\x12\x33\n\x10sms_notification\x18\x02 \x01(\x0b\x32\x19.apexnova.SMSNotification\"Q\n\x18SendNotificationResponse\x12\x35\n\x11standard_response\x18\x01 \x01(\x0b\x32\x1a.apexnova.StandardResponse2\xab\x01\n\x13NotificationService\x12K\n\tSendEmail\x12\x1a.apexnova.SendEmailRequest\x1a\".apexnova.SendNotificationResponse\x12G\n\x07SendSMS\x12\x18.apexnova.SendSMSRequest\x1a\".apexnova.SendNotificationResponseB7\n\x19\x63om.apexnova.notificationB\x18NotificationServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apexnova.notification.notification_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.apexnova.notificationB\030NotificationServiceProtoP\001'
  _globals['_SENDEMAILREQUEST']._serialized_start=178
  _globals['_SENDEMAILREQUEST']._serialized_end=316
  _globals['_SENDSMSREQUEST']._serialized_start=319
  _globals['_SENDSMSREQUEST']._serialized_end=451
  _globals['_SENDNOTIFICATIONRESPONSE']._serialized_start=453
  _globals['_SENDNOTIFICATIONRESPONSE']._serialized_end=534
  _globals['_NOTIFICATIONSERVICE']._serialized_start=537
  _globals['_NOTIFICATIONSERVICE']._serialized_end=708
# @@protoc_insertion_point(module_scope)
