
def permission_message_return(language: str, message: str) -> str: ...

def detail_message_return(language: str, message: str) -> dict: ...

def msg_message_return(language: str, message: str) -> dict: ...

def login_message_return(language: str, message: str) -> dict: ...

def others_message_return(language: str, message: str) -> str: ...