#ifndef SSRJSON_ENCODE_INDENT_WRITER_H
#define SSRJSON_ENCODE_INDENT_WRITER_H


#define COMPILE_INDENT_LEVEL 0
#define COMPILE_WRITE_UCS_LEVEL 1
#include "_indent.inl.h"
#undef COMPILE_WRITE_UCS_LEVEL
#undef COMPILE_INDENT_LEVEL

#define COMPILE_INDENT_LEVEL 0
#define COMPILE_WRITE_UCS_LEVEL 2
#include "_indent.inl.h"
#undef COMPILE_WRITE_UCS_LEVEL
#undef COMPILE_INDENT_LEVEL

#define COMPILE_INDENT_LEVEL 0
#define COMPILE_WRITE_UCS_LEVEL 4
#include "_indent.inl.h"
#undef COMPILE_WRITE_UCS_LEVEL
#undef COMPILE_INDENT_LEVEL

#define COMPILE_INDENT_LEVEL 2
#define COMPILE_WRITE_UCS_LEVEL 1
#include "_indent.inl.h"
#undef COMPILE_WRITE_UCS_LEVEL
#undef COMPILE_INDENT_LEVEL

#define COMPILE_INDENT_LEVEL 2
#define COMPILE_WRITE_UCS_LEVEL 2
#include "_indent.inl.h"
#undef COMPILE_WRITE_UCS_LEVEL
#undef COMPILE_INDENT_LEVEL

#define COMPILE_INDENT_LEVEL 2
#define COMPILE_WRITE_UCS_LEVEL 4
#include "_indent.inl.h"
#undef COMPILE_WRITE_UCS_LEVEL
#undef COMPILE_INDENT_LEVEL

#define COMPILE_INDENT_LEVEL 4
#define COMPILE_WRITE_UCS_LEVEL 1
#include "_indent.inl.h"
#undef COMPILE_WRITE_UCS_LEVEL
#undef COMPILE_INDENT_LEVEL

#define COMPILE_INDENT_LEVEL 4
#define COMPILE_WRITE_UCS_LEVEL 2
#include "_indent.inl.h"
#undef COMPILE_WRITE_UCS_LEVEL
#undef COMPILE_INDENT_LEVEL

#define COMPILE_INDENT_LEVEL 4
#define COMPILE_WRITE_UCS_LEVEL 4
#include "_indent.inl.h"
#undef COMPILE_WRITE_UCS_LEVEL
#undef COMPILE_INDENT_LEVEL


#endif // SSRJSON_ENCODE_INDENT_WRITER_H
