"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from tofupilot_py.types import BaseModel
from tofupilot_py.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class UnitDeleteRequestTypedDict(TypedDict):
    serial_number: str
    r"""The serial number of the unit"""


class UnitDeleteRequest(BaseModel):
    serial_number: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The serial number of the unit"""


class UnitDeleteResponseTypedDict(TypedDict):
    r"""Unit deleted successfully"""

    serial_number: str
    r"""The serial number of the unit"""


class UnitDeleteResponse(BaseModel):
    r"""Unit deleted successfully"""

    serial_number: str
    r"""The serial number of the unit"""
