"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from tofupilot_py.types import BaseModel
from typing_extensions import TypedDict


class UploadSyncUploadRequestTypedDict(TypedDict):
    upload_id: str
    r"""The ID of the upload to sync"""
    run_id: str
    r"""The ID of the run to link the upload to"""


class UploadSyncUploadRequest(BaseModel):
    upload_id: str
    r"""The ID of the upload to sync"""

    run_id: str
    r"""The ID of the run to link the upload to"""


class UploadSyncUploadResponseTypedDict(TypedDict):
    r"""Upload synced successfully"""


class UploadSyncUploadResponse(BaseModel):
    r"""Upload synced successfully"""
