double dmax(double,double);
double dmin(double,double);
double drand48();
void   endrun(int);
int    imax(int,int);
int    imin(int,int);
double second(void);
double timediff(double t0,double t1); 
void m_multiply(float **a, float **b,float **c,int ,int , int);
void m_print(float **a,int ,int);
void m_copy(float **a,float **b,int , int, int);
void a_copy(float *a,float *b,int , int);
void a_print(float *a,int , int);
float a_max(float *a,int n1 , int n2);
float a_min(float *a,int n1 , int n2);
void m_multiply_a(float **a, float *b,float *c,int , int ,int );
double pow(double, double);
float gammln(float xx);
void   checkrun(string s1,string s2,string s3);
void   endrunm(string s);
