# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dev_observer/api/types/config.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'dev_observer/api/types/config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dev_observer.api.types import observations_pb2 as dev__observer_dot_api_dot_types_dot_observations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#dev_observer/api/types/config.proto\x12\x1d\x64\x65v_observer.api.types.config\x1a)dev_observer/api/types/observations.proto\"\x99\x01\n\x0cGlobalConfig\x12?\n\x08\x61nalysis\x18\x01 \x01(\x0b\x32-.dev_observer.api.types.config.AnalysisConfig\x12H\n\rrepo_analysis\x18\x02 \x01(\x0b\x32\x31.dev_observer.api.types.config.RepoAnalysisConfig\"\xb7\x01\n\x0e\x41nalysisConfig\x12\x45\n\x0erepo_analyzers\x18\x01 \x03(\x0b\x32-.dev_observer.api.types.observations.Analyzer\x12\x45\n\x0esite_analyzers\x18\x02 \x03(\x0b\x32-.dev_observer.api.types.observations.Analyzer\x12\x17\n\x0f\x64isable_masking\x18\x03 \x01(\x08\"W\n\x14UserManagementStatus\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\x12\x1b\n\x0epublic_api_key\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x11\n\x0f_public_api_key\"\x8c\x03\n\x12RepoAnalysisConfig\x12J\n\x07\x66latten\x18\x01 \x01(\x0b\x32\x39.dev_observer.api.types.config.RepoAnalysisConfig.Flatten\x12\x1f\n\x17processing_interval_sec\x18\x02 \x01(\x05\x12\x10\n\x08\x64isabled\x18\x03 \x01(\x08\x1a\xf6\x01\n\x07\x46latten\x12\x10\n\x08\x63ompress\x18\x01 \x01(\x08\x12\x1a\n\x12remove_empty_lines\x18\x02 \x01(\x08\x12\x11\n\tout_style\x18\x03 \x01(\t\x12\x1c\n\x14max_tokens_per_chunk\x18\x04 \x01(\x05\x12\x18\n\x10max_repo_size_mb\x18\x05 \x01(\x05\x12\x16\n\x0eignore_pattern\x18\x06 \x01(\t\x12\x1f\n\x17large_repo_threshold_mb\x18\x07 \x01(\x05\x12!\n\x19large_repo_ignore_pattern\x18\x08 \x01(\t\x12\x16\n\x0e\x63ompress_large\x18\t \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dev_observer.api.types.config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GLOBALCONFIG']._serialized_start=114
  _globals['_GLOBALCONFIG']._serialized_end=267
  _globals['_ANALYSISCONFIG']._serialized_start=270
  _globals['_ANALYSISCONFIG']._serialized_end=453
  _globals['_USERMANAGEMENTSTATUS']._serialized_start=455
  _globals['_USERMANAGEMENTSTATUS']._serialized_end=542
  _globals['_REPOANALYSISCONFIG']._serialized_start=545
  _globals['_REPOANALYSISCONFIG']._serialized_end=941
  _globals['_REPOANALYSISCONFIG_FLATTEN']._serialized_start=695
  _globals['_REPOANALYSISCONFIG_FLATTEN']._serialized_end=941
# @@protoc_insertion_point(module_scope)
