
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-06-27T16:16:43+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b9cd9b266996497c0114d0e6b7426790274d0f93",
 "version": "1.0.0a4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
