
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-06-27T16:04:02+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e066fffa9dd7f65769e62a638a8b55659eae70d0",
 "version": "2.0.3a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
