#+title: bisos.cntnr:  Python Command-Services forBISOS Container Abstractions

Panel Controls:: [[elisp:(show-all)][Show-All]]  [[elisp:(org-shifttab)][Overview]]  [[elisp:(progn (org-shifttab) (org-content))][Content]] | [[elisp:(delete-other-windows)][(1)]] | [[elisp:(progn (save-buffer) (kill-buffer))][S&Q]] [[elisp:(save-buffer)][Save]] [[elisp:(kill-buffer)][Quit]] [[elisp:(bury-buffer)][Bury]]
Links: [[file:./panels/_nodeBase_/fullUsagePanel-en.org]] (Package Panel)

* Overview
bisos.cntnr is a python package that uses the PyCS-Framework for BISOS Container Abstractions.
It is a BISOS-Capability and a Standalone-BISOS-Package.

/bisos.cntnr/ is based on PyCS-Foundation and can be used both as a Command and
as a Service (invoke/perform model of remote operations) using RPYC for central
management of multiple systems.


* Table of Contents     :TOC:
- [[#overview][Overview]]
- [[#about-bisos-----bystar-internet-services-operating-system][About BISOS --- ByStar Internet Services Operating System]]
- [[#bisoscntnr-is-a-command-services-pycs-facility][bisos.cntnr is a Command Services (PyCS) Facility]]
-  [[#uses-of-bisoscntnr][Uses of bisos.cntnr]]
- [[#bisoscntnr-as-a-standalone-piece-of-bisos][bisos.cntnr as a Standalone Piece of BISOS]]
- [[#installation][Installation]]
  - [[#with-pip][With pip]]
  - [[#with-pipx][With pipx]]
- [[#usage][Usage]]
  - [[#locally-system-command-line][Locally (system command-line)]]
  - [[#remotely-as-a-service----performerinvoker][Remotely (as a service -- Performer+Invoker)]]
    - [[#performer][Performer]]
    - [[#invoker][Invoker]]
  - [[#use-by-python-script][Use by Python script]]
    - [[#bisoscntnr-source-code-is-in-writen-in-comeega-collaborative-org-mode-enhanced-emacs-generalized-authorship----httpsgithubcombx-bleecomeega][bisos.cntnr Source Code is in writen in COMEEGA (Collaborative Org-Mode Enhanced Emacs Generalized Authorship) -- https://github.com/bx-blee/comeega.]]
    - [[#the-primary-api-for-bisoscntnr-is-bisoscntnrcntnr-csupy-it-is-self-documented-in-comeega][The primary API for bisos.cntnr is ./bisos/cntnr/cntnr-csu.py. It is self documented in COMEEGA.]]
- [[#documentation-and-blee-panels][Documentation and Blee-Panels]]
  - [[#bisoscntnr-blee-panels][bisos.cntnr Blee-Panels]]
- [[#support][Support]]

* About BISOS --- ByStar Internet Services Operating System

Layered on top of Debian, *BISOS*: (By* Internet Services Operating System) is a
unified and universal framework for developing both internet services and
software-service continuums that use internet services. See [[https://github.com/bxGenesis/start][Bootstrapping
ByStar, BISOS and Blee]] for information about getting started with BISOS.

/bisos.cntnr/ as a PyCS facility is a small piece of a much bigger picture. *BISOS*
is a foundation for *The Libre-Halaal ByStar Digital Ecosystem* which is described
as a cure for losses of autonomy and privacy that we are experiencing in a book
titled: [[https://github.com/bxplpc/120033][Nature of Polyexistentials]]

* bisos.cntnr is a Command Services (PyCS) Facility

bisos.cntnr can be used locally on command-line or remotely as a service.
bisos.cntnr is a PyCS multi-unit command-service.
PyCS is a framework that converges developement of CLI and Services.
PyCS is an alternative to FastAPI, Typer and Click.

bisos.cntnr uses the PyCS Framework to:

1) Provide access to cntnr facilities through native python.
2) Provide local access to cntnr facilities on CLI.
3) Provide remote access to cntnr facilities through remote invocation of
   python Expection Complete Operations using [[https://github.com/tomerfiliba-org/rpyc][rpyc]].
4) Provide remote access to cntnr facilities on CLI.

What is unique in the PyCS-Framework is that these four models are all
a single abstraction.

The core of PyCS-Framework is the /bisos.b/ package (the PyCS-Foundation).
See https://github.com/bisos-pip/b for an overview.

*  Uses of bisos.cntnr

Within BISOS,  bisos.cntnr is used as a common facility.


* bisos.cntnr as a Standalone Piece of BISOS

bisos.cntnr is a standalone piece of BISOS. It can be used as a self-contained
Python package separate from BISOS. Follow the installtion and usage
instructions below for your own use.

* Installation

The sources for the  bisos.cntnr pip package is maintained at:
https://github.com/bisos-pip/cntnr.

The bisos.cntnr pip package is available at PYPI as
https://pypi.org/project/bisos.cntnr

You can install bisos.cntnr with pip or pipx.

** With pip

If you need access to bisos.cntnr as a python module, you can install it with pip:

#+begin_src bash
pip install bisos.cntnr
#+end_src

** With pipx

If you only need access to bisos.cntnr as a command on command-line, you can install it with pipx:

#+begin_src bash
pipx install bisos.cntnr
#+end_src

The following commands are made available:
- cntnr.cs
- roInv-cntnr.cs
- roPerf-cntnr.cs

These are all one file with 3 names. _roInv-cntnr.cs_ and _roPerf-cntnr.cs_ are sym-links to _cntnr.cs_

* Usage

** Locally (system command-line)

=cntnr.cs= can be invoked directly as

#+begin_src bash
bin/cntnr.cs
#+end_src

** Remotely (as a service -- Performer+Invoker)

You can also  run


*** Performer

Run performer as:

#+begin_src bash
bin/roPerf-cntnr.cs
#+end_src

*** Invoker

Run invoker as:

#+begin_src bash
bin/roInv-cntnr.cs
#+end_src

** Use by Python script

*** bisos.cntnr Source Code is in writen in COMEEGA (Collaborative Org-Mode Enhanced Emacs Generalized Authorship) -- https://github.com/bx-blee/comeega.

*** The primary API for bisos.cntnr is ./bisos/cntnr/cntnr-csu.py. It is self documented in COMEEGA.

* Documentation and Blee-Panels

bisos.cntnr is part of ByStar Digital Ecosystem [[http://www.by-star.net]].

This module's primary documentation is in the form of Blee-Panels.
Additional information is also available in: [[http://www.by-star.net/PLPC/180047]]

** bisos.cntnr Blee-Panels

bisos.cntnr Blee-Panles are in ./panels directory.
From within Blee and BISOS these panles are accessible under the
Blee "Panels" menu.

* Support

For support, criticism, comments and questions; please contact the
author/maintainer\\
[[http://mohsen.1.banan.byname.net][Mohsen Banan]] at:
[[http://mohsen.1.banan.byname.net/contact]]


